version: "3.8"

services:
  db:
    image: "postgres:14-bullseye"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - poozle
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: engine-server
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: poozle-server
    depends_on:
      - db
      - supertokens
    restart: unless-stopped
    ports:
      - 3009:3000
    networks:
      - poozle
    environment:
      - ENGINE_VERSION=${ENGINE_VERSION}
      - DATABASE_URL=${DATABASE_URL}
      - SYNC_DATABASE_URL=${SYNC_DATABASE_URL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - PUBLIC_FRONTEND_HOST=${PUBLIC_FRONTEND_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PORT=${PORT}
      - MASTER_TOKEN=${TOKEN}

networks:
  app_network:
    driver: bridge
  poozle: {}

volumes:
  postgres-data:
