name: Build Artifacts

on:
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: ./engine-server
          push: false
          cache-from: type=gha,scope=dev
          cache-to: type=gha,mode=max,scope=dev
