name: Build and Push Artifacts
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }} # Add your cluster name here.
  GKE_ZONE: ${{ secrets.GKE_ZONE }} # Add your cluster zone here.
  HELM_GCS_REPOSITORY: gs://levoai-private-helm-charts
  BASE_VERSION: 0.1.
  GHCR_IMAGE_ID: ghcr.io/levoai/poozle/poozle-engine-server

on:
  push:
    branches:
      - main

jobs:
  build-and-push-dev-image:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - id: get_version
        run: echo "VERSION=${BASE_VERSION}${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./engine-server
          push: true
          tags: ${{ env.GHCR_IMAGE_ID }}:${{ steps.get_version.outputs.version }}
          cache-from: type=gha,scope=dev
          cache-to: type=gha,mode=max,scope=dev

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure() || cancelled()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
